### ISSUE TITLE
Error for 3D when using p4est 2.8.5

### ISSUE THREAD

**Issue by JordiManyer** [gridap/GridapP4est.jl#49]
Tests for 3D are failing very early on when using more modern p4est releases. 
**Note:** I am not sure for which version this starts failing, I've only tested versions 2.2 and 2.8.5. 

So here is my analysis of the issue: 

In p4est, the `p8est_tree_t` type is defined [here](https://github.com/cburstedde/p4est/blob/aee0bf1ccccfbcaeba53beb38688b1d4fc3da8ab/src/p8est.h#L118C50-L118C50), and it's variable `quadrants_per_level` is set as an array of length `P8EST_MAXLEVEL+1`. 

In `P4est_wrapper.jl`, the structure that is meant to replicate it is defined [here](https://github.com/gridap/P4est_wrapper.jl/blob/c6db4f402c5a7db76349d6fb0380c065eefe6188/src/bindings/p8est_common.jl#L24). The maximum number of levels is set to 19. 

For p4est v2.8.5, we have that `P8EST_MAXLEVEL=30`, whereas in p4est 2.2 it was indeed 19. I suspect this is meant to increase consistency between the p4est and p8est implementations (now both have same number of max levels). 

So a new version of P4est_wrapper is necessary to correct these changes.

**Comment by JordiManyer** [comment]
Hi @wei3li . What version of p4est are you using? If it is the same error, I have it fixed on a branch of P4est_wrapper.jl

**Comment by wei3li** [comment]
Hi @JordiManyer, thank you! Branch p4est_2.3+ of P4est_wrapper.jl works for me.
